### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by glenfordwilliams** [PySide/pyside2-setup#1]
is it possible for the build instructions to be updated? im very much interested in helping out where possible whether it be testing or writing code

**Comment by IronManMark20** [comment]
There is already discussion of this [here](https://github.com/PySide/pyside2/issues/2). Re-posting what I said earlier:

1. Get OpenSSL, cmake, and Qt 5.4.x (seems Christian and I are both using 5.4.2). This is very platform dependent. It should be very similar to [these instructions](https://pyside.readthedocs.org/en/latest/building/index.html), except you should get Qt from [the archives](https://download.qt.io/archive/qt/5.4/5.4.2/)
2. `git clone --recursive https://github.com/PySide/pyside-setup2.git`
3. `cd pyside-setup2`
4. `python.exe setup.py install --qmake=/path/to/bin/qmake --cmake=/path/to/bin/cmake --openssl=/path/to/openssl/bin --ignore-git`. Note that the `qmake` and `cmake` are looking for something to execute, but openssl is just looking for the bin folder. 

Some notes for Windows. Between steps 3 and 4, you should `cd sources && cd pyside2` so that you can `git checkout qt5-win-fix`, which allows you to compile PySide2.

What platform(s) are you building for?

It would be easier to just move all discussion over to the other issue, but if you have any questions on building, I can see what I can do. Note that this is alpha quality software. I have had to do a few work arounds to get a simple Window showing. That said, if you want to help, that seems to be exactly what Christian (the creator of this project) is looking for.

**Comment by glenfordwilliams** [comment]
@IronManMark20  thanks for the help but im having issues building for windows

`Package version: 2.0.0.dev0
Build type: Release
Build tests: False
---
Make path: C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe
Make generator: NMake Makefiles
Make jobs:
---
Script directory: C:\Users\Williams\pyside2-setup
Sources directory: C:\Users\Williams\pyside2-setup\sources
Build directory: C:\Users\Williams\pyside2-setup\pyside_build\py3.4-qt5.5.0-32bit-release
Install directory: C:\Users\Williams\pyside2-setup\pyside_install\py3.4-qt5.5.0-32bit-release
Python site-packages install directory: C:\Users\Williams\pyside2-setup\pyside_install\py3.4-qt5.5.0-32bit-release\Lib\site-packages
---
Python executable: C:\python34_32\python.exe
Python includes: C:\python34_32\include
Python library: C:\python34_32\libs\python34.lib
Python prefix: C:\python34_32
Python scripts: C:\python34_32\Scripts
---
Qt qmake: C:\Qt\5.5\msvc2010\bin\qmake.exe
Qt version: 5.5.0
Qt bins: C:/Qt/5.5/msvc2010/bin
Qt docs: C:/Qt/Docs/Qt-5.5
Qt plugins: C:/Qt/5.5/msvc2010/plugins
---
OpenSSL libs: C:\Program Files\OpenSSL\bin\openssl
==============================
Building module shiboken2...
Deleting module build folder C:\Users\Williams\pyside2-setup\pyside_build\py3.4-qt5.5.0-32bit-release\shiboken2...
Creating module build folder C:\Users\Williams\pyside2-setup\pyside_build\py3.4-qt5.5.0-32bit-release\shiboken2...
Configuring module shiboken2 (C:\Users\Williams\pyside2-setup\sources\shiboken2)...
Running process: "C:\Program Files (x86)\CMake\bin\cmake.exe" -G "NMake Makefiles" -DQT_QMAKE_EXECUTABLE=C:\Qt\5.5\msvc2010\bin\qmake.exe -DBUILD_TESTS=False -DDISABLE_DOCSTRINGS=True -DQt5Help_DIR=C:/Qt/Docs/Qt-5.5 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=C:\Users\Williams\pyside2-setup\pyside_install\py3.4-qt5.5.0-32bit-release C:\Users\Williams\pyside2-setup\sources\shiboken2 -DPYTHON3_EXECUTABLE=C:\python34_32\python.exe -DPYTHON3_INCLUDE_DIR=C:\python34_32\include -DPYTHON3_LIBRARY=C:\python34_32\libs\python34.lib -DCMAKE_DEBUG_POSTFIX=_d -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DUSE_PYTHON3=ON
-- The C compiler identification is MSVC 16.0.30319.1
-- The CXX compiler identification is MSVC 16.0.30319.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3Libs: C:/Python34_32/libs/python34.lib
-- Found Python3Interp: C:/Python34_32/python.exe
-- Could NOT find Python3InterpDbg (missing:  PYTHON3_DBG_EXECUTABLE)
-- Could NOT find Python3InterpDbg (missing:  PYTHON3_DBG_EXECUTABLE)
PYTHON WITH DEBUG: C:/Python34_32/python.exe
-- Could NOT find LibXml2 (missing:  LIBXML2_LIBRARIES LIBXML2_INCLUDE_DIR) (Required is at least version "2.6.32")
-- Could NOT find LibXslt (missing:  LIBXSLT_LIBRARIES LIBXSLT_INCLUDE_DIR) (Required is at least version "1.1.19")
-- sphinx-build - not found! doc target disabled
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_DEBUG_POSTFIX
    QT_QMAKE_EXECUTABLE
    Qt5Help_DIR


-- Build files have been written to: C:/Users/Williams/pyside2-setup/pyside_build/py3.4-qt5.5.0-32bit-release/shiboken2
Compiling module shiboken2...
Running process: "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.exe"

Microsoft (R) Program Maintenance Utility Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

Scanning dependencies of target apiextractor_automoc
[  1%] Automatic moc for target apiextractor
[  1%] Built target apiextractor_automoc
[  3%] Generating qrc_generator.cpp
Scanning dependencies of target apiextractor
[  5%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/apiextractor.cpp.obj
apiextractor.cpp
[  6%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/abstractmetabuilder.cpp.obj
abstractmetabuilder.cpp
[  8%] Building CXX object ApiExtractor/CMakeFiles/apiextractor.dir/abstractmetalang.cpp.obj
abstractmetalang.cpp
C:\Users\Williams\pyside2-setup\sources\shiboken2\ApiExtractor\abstractmetalang.cpp(2382) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'msc1.cpp', line 1420)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
Internal Compiler Error in C:\PROGRA~2\MICROS~4.0\VC\bin\cl.exe.  You will be prompted to send an error report to Microsoft later.
error: Error compiling shiboken2
`

**Comment by IronManMark20** [comment]
@glenfordwilliams It seems the Visual Studio compiler had an internal error. Are you getting this repeatedly?

**Comment by glenfordwilliams** [comment]
yes i am

**Comment by ctismer** [comment]
For me it works. I suspect that you are missing a service pack?

**Comment by glenfordwilliams** [comment]
do i have to use this version of visual studio?

**Comment by ctismer** [comment]
I have used VS2010 with service pack. For other compilers, you tell me, instead of asking.

**Comment by glenfordwilliams** [comment]
@ctismer i ended up reinstalling visual studio and so far all is well.i do have genuine interest in assisting with the port so after testing ill see where i can be of use to the project

**Comment by ctismer** [comment]
@glenfordwilliams ah, fine that it is fixed. Thanks for any help.
