### ISSUE TITLE
Minimal Qt version?

### ISSUE THREAD

**Issue by The-Compiler** [pyside/pyside2-setup#13]
I don't see the minimal Qt version documented anywhere - will 5.2 (comes with Ubuntu Trusty on Travis CI) work?

The comment in `setup.py` still says:

> - Qt: 4.6, 4.7 and 4.8 is supported.

**Comment by IronManMark20** [comment]
In previous discussions, I believe the versions we have used are Qt 5.4 and Qt5.5. I do not know of plans to support below 5.4. I don't think 5.2/5.3 will break compatibility. You can always try it.

**Comment by cmaureir** [comment]
not valid anymore.
