### ISSUE TITLE
Improved logging for Git subcommands

### ISSUE THREAD

**Issue by techtonik** [pyside/pyside2-setup#16]
I don't understand why it fails. Is it possible to get more descriptive log for that?

```
> py setup.py install -h
Initializing submodules for PySide2 version 2.0.0.dev0
Traceback (most recent call last):
  File "setup.py", line 253, in <module>
    raise DistutilsSetupError("Failed to initialize the git submodules")
distutils.errors.DistutilsSetupError: Failed to initialize the git submodules
```

**Comment by IronManMark20** [comment]
After looking at the [line 253](https://github.com/PySide/pyside2-setup/blob/master/setup.py#L253), this is an error with pulling submodules. I recommend that you attempt the command that was being called (`git submodule foreach git pull origin master`). If that succeeds, you can add the temporary flag `--ignore-git`, which will ignore the git calls, which you should be fine doing. Just make sure your on the latest commit.

**Comment by techtonik** [comment]
It says `
*** Please tell me who you are.
` at the end.

**Comment by IronManMark20** [comment]
This means you need to identify yourself in git.

Please see [the git docs](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity) on setting up git with an identity.

**Comment by techtonik** [comment]
I know.

**Comment by techtonik** [comment]
Why I need to setup my username anyway? Plain `git clone` doesn't need it.

**Comment by thopiekar** [comment]
I also don't understand it. ```git``` just asks for the username when creating a first ```commit```. ```pull```'ing should always work.

**Comment by cmaureir** [comment]
invalid
