### ISSUE TITLE
Error compiling shiboken2

### ISSUE THREAD

**Issue by micaelr95** [PySide/pyside2-setup#21]
While compiling pyside2 in linux mint 17.3 i receive this error: Error compiling shiboken2.

I'm using this command to compile sudo python3 setup.py install --qmake=/usr/bin/qmake --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl/bin

And here is the log
[log.txt](https://github.com/PySide/pyside2-setup/files/102045/log.txt)

**Comment by thopiekar** [comment]
Can you  make a complete copy of your outputs? I just can't see any error message.

**Comment by micaelr95** [comment]
The new log don't show everything (i'm using kde and i don't know much about it) but i think te essential is here
[log.txt](https://github.com/PySide/pyside2-setup/files/102125/log.txt)

**Comment by thopiekar** [comment]
Ok, this should be fixed. I guess we should make setup.py prefer "qmake-qt5" over "qmake".

**Comment by ctismer** [comment]
nice!

**Comment by AlchemistRS** [comment]
I'm having a similar problem but in Windows10 x64 using Qt 5.6.1, Python2.7.11 x64 standard version and also tried Python2.7.10 x64 msvs15. I get the same errors when trying to build PySide2. If anyone can help me out or point me in the right direction it will be Greatly appreciated. Attached are the logs two logs.

[py27vs15 Log.txt](https://github.com/pyside/pyside2-setup/files/854199/py27vs15.Log.txt)
[py27stn Log.txt](https://github.com/pyside/pyside2-setup/files/854200/py27stn.Log.txt)

**Comment by thopiekar** [comment]
@AlchemistRS Hope you are not using the old sources.
However, better use QtCompany's bugtracker to report bugs 😉

**Comment by AlchemistRS** [comment]
thopiekar you mean the old sources of Qt or PySide-Setup? I also tried with py35 got the same error here is the log.
[py35 Log.txt](https://github.com/pyside/pyside2-setup/files/854238/py35.Log.txt)

Thanks for the quick response

**Comment by thopiekar** [comment]
Mean both. PySide2 is now hosted at QtCompany's own Git server.
Don't know how often GitHub gets synchronized.

You can find a list of URLs here: https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git

**Comment by AlchemistRS** [comment]
Thanks 
thopiekar
I'll check the out 
Thanks Again

**Comment by thopiekar** [comment]
no problem :)
