### ISSUE TITLE
Open team account on AppVeyor

### ISSUE THREAD

**Issue by techtonik** [PySide/pyside2-setup#24]
* [ ] open team account https://www.appveyor.com/docs/team-setup 
* [ ] setup builds for pyside2-setup
* [ ] update README.md link

@ctismer can you setup a team there to move builds from

  https://ci.appveyor.com/project/techtonik/pyside2-setup
to
  https://ci.appveyor.com/project/pyside/pyside2-setup

(continuation of #17)

**Comment by ctismer** [comment]
Oups, I fear that takes to much of my small-brain during the week.
Can you please remind me on Friday/Weekend? I'm completely into something different right now ;-)

**Comment by techtonik** [comment]
@ctismer reminding. =)

**Comment by techtonik** [comment]
@ctismer so how it goes?

**Comment by IronManMark20** [comment]
I think I have permissions to do this, so to make things easier @ctismer do you want me to set up an Appveyor build setup?

**Comment by thopiekar** [comment]
Go for it :smile:

**Comment by ethanhs** [comment]
So this now seems impossible as the builds on appveyor are not fast enough, and I think all the CI stuff is being moved over to Qt anyway.

**Comment by techtonik** [comment]
@ethanhs so how do you propose to CI test Windows builds then? Does Qt Project provide any facilities? Otherwise we can think about caching parts of the build process. It is not okay that it takes so long anyway.

**Comment by ethanhs** [comment]
The Qt Company as part of making PySide an officially supported product, is working on CI for it. The github project is now essentially dead as all development has moved to the Qt Company's infrastructure.

**Comment by techtonik** [comment]
@ethanhs can you share more details about that? Do they hire people from community?

**Comment by ethanhs** [comment]
First of all, I don't know if you saw [this post](https://groups.google.com/forum/#!topic/pyside-dev/pqwzngAGLWE). Secondly, they hired ctismer to work on it, but that is all I know of. I think the Qt devs are open to community contributions. Anyway, if you want to discuss this further perhaps chat such as [gitter](https://gitter.im) is better.
