### ISSUE TITLE
Python str compatibility issue with pyside-rcc

### ISSUE THREAD

**Issue by shravan14k** [PySide/pyside2-setup#30]
I just compiled pyside2 on Windows (python 3.4, Qt 5.5.1). and wrote an application. I compiled the `.qrc` file to a `.py` using `pyside-rcc` (found in `C:\Python34\Lib\site-packages\PySide2-2.0.0.dev0-py3.4-win32.egg\PySide2\pyside-rcc.exe`). But when I try to run it, I get this error:

    TypeError: 'qRegisterResourceData' called with wrong argument types:
      qRegisterResourceData(int, str, str, str)
    Supported signatures:
      qRegisterResourceData(int, unicode, unicode, unicode)

I also tried to run a few of the examples (the ones in `C:\Python34\Lib\site-packages\PySide2-2.0.0.dev0-py3.4-win32.egg\PySide2\examples`) but got the same error. Why am I having to deal with `unicode`?? And, how can I get rid of the error?

**Comment by looooo** [comment]
Use -py3 option when running the pyside-rcc command.

**Comment by shravan14k** [comment]
@looooo Oh, thanks man. It worked.
