### ISSUE TITLE
Access Denied - installation

### ISSUE THREAD

**Issue by RodrigoBonas** [pyside/pyside2-setup#35]
I run the command prompt as administrator.
But in the installation i have access denied. Why?

C:\lib\pyside2>C:\Python34\python.exe setup.py install --qmake="C:\Qt\Qt5.5.1\5.5\msvc2010\bin" --cmake="C:\Program Files (x86)\CMake\bin" --openssl="C:\OpenSSL-Win32\bin"
Removing C:\lib\pyside2\pyside_package
running install
running bdist_egg
running build
Python architecture is 32bit
nmake not found. Trying to initialize the MSVC env...
Searching MSVC compiler version 10.0
Found C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\
Searching MSVC compiler 10.0 environment init script
Found C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat
Using MSVC 10.0 in C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat
Getting MSVC env for x86 architecture
Initializing MSVC env...
Inserting path "C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\" to environment
Inserting path "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN" to environment
Inserting path "C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools" to environment
Inserting path "C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319" to environment
Inserting path "C:\WINDOWS\Microsoft.NET\Framework\v3.5" to environment
Inserting path "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\VCPackages" to environment
Inserting path "C:\Program Files (x86)\HTML Help Workshop" to environment
Inserting path "C:\Program Files (x86)\HTML Help Workshop" to environment
Inserting path "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools" to environment
Inserting path "C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin" to environment
Inserting "ALLUSERSPROFILE = C:\ProgramData" to environment
Inserting "APPDATA = C:\Users\R\AppData\Roaming" to environment
Inserting "COMPUTERNAME = R-PC" to environment
Inserting "C_EM64T_REDIST11 = C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\" to environment
Inserting "ComSpec = C:\WINDOWS\system32\cmd.exe" to environment
Inserting "CommonProgramFiles = C:\Program Files (x86)\Common Files" to environment
Inserting "CommonProgramFiles(x86) = C:\Program Files (x86)\Common Files" to environment
Inserting "CommonProgramW6432 = C:\Program Files\Common Files" to environment
Inserting "DevEnvDir = C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\IDE\" to environment
Inserting "Framework35Version = v3.5" to environment
Inserting "FrameworkDIR32 = C:\WINDOWS\Microsoft.NET\Framework\" to environment
Inserting "FrameworkDir = C:\WINDOWS\Microsoft.NET\Framework\" to environment
Inserting "FrameworkVersion = v4.0.30319" to environment
Inserting "FrameworkVersion32 = v4.0.30319" to environment
Inserting "HOMEDRIVE = C:" to environment
Inserting "HOMEPATH = \Users\R" to environment
Inserting "INCLUDE = C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\include;" to environment
Inserting "LIB = C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\lib;" to environment
Inserting "LIBPATH = C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319;C:\WINDOWS\Microsoft.NET\Framework\v3.5;C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\LIB;" to environment
Inserting "LOCALAPPDATA = C:\Users\R\AppData\Local" to environment
Inserting "LOGONSERVER = \R-PC" to environment
Inserting "NUMBER_OF_PROCESSORS = 4" to environment
Inserting "OPENSSL_CONF = C:\OpenSSL\bin\openssl.cfg" to environment
Inserting "OS = Windows_NT" to environment
Inserting "PATHEXT = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY" to environment
Inserting "PLAT = win32" to environment
Inserting "PROCESSOR_ARCHITECTURE = x86" to environment
Inserting "PROCESSOR_ARCHITEW6432 = AMD64" to environment
Inserting "PROCESSOR_IDENTIFIER = Intel64 Family 6 Model 42 Stepping 7, GenuineIntel" to environment
Inserting "PROCESSOR_LEVEL = 6" to environment
Inserting "PROCESSOR_REVISION = 2a07" to environment
Inserting "PROMPT = $P$G" to environment
Inserting "PSModulePath = C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\" to environment
Inserting "PUBLIC = C:\Users\Public" to environment
Inserting "ProgramData = C:\ProgramData" to environment
Inserting "ProgramFiles = C:\Program Files (x86)" to environment
Inserting "ProgramFiles(x86) = C:\Program Files (x86)" to environment
Inserting "ProgramW6432 = C:\Program Files" to environment
Inserting "SystemDrive = C:" to environment
Inserting "SystemRoot = C:\WINDOWS" to environment
Inserting "TEMP = C:\Users\R\AppData\Local\Temp" to environment
Inserting "TMP = C:\Users\R\AppData\Local\Temp" to environment
Inserting "USERDOMAIN = R-PC" to environment
Inserting "USERDOMAIN_ROAMINGPROFILE = R-PC" to environment
Inserting "USERNAME = R" to environment
Inserting "USERPROFILE = C:\Users\R" to environment
Inserting "VBOX_MSI_INSTALL_PATH = C:\Program Files\Oracle\VirtualBox\" to environment
Inserting "VCINSTALLDIR = C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\" to environment
Inserting "VS100COMNTOOLS = C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools\" to environment
Inserting "VS110COMNTOOLS = C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\" to environment
Inserting "VS120COMNTOOLS = C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\" to environment
Inserting "VS140COMNTOOLS = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\" to environment
Inserting "VSINSTALLDIR = C:\Program Files (x86)\Microsoft Visual Studio 10.0\" to environment
Inserting "VSSDK140Install = C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\" to environment
Inserting "WindowsSdkDir = C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\" to environment
Inserting "windir = C:\WINDOWS" to environment
Done initializing MSVC env
error: [WinError 5] Access denied

**Comment by IronManMark20** [comment]
Perhaps the issue is that it is getting access denied trying to access nmake? Can you try running the same from the visual studio 2010 command prompt (as admin)? It may be a temporary workaround to have nmake in your path.

**Comment by bkerler** [comment]
You need to give the full path to the binaries. Access denied means it cannot find the executable to run.  For your example, you need to : >C:\Python34\python.exe setup.py install --qmake="C:\Qt\Qt5.5.1\5.5\msvc2010\bin\qmake.exe" --cmake="C:\Program Files (x86)\CMake\bin\cmake.exe" --openssl="C:\OpenSSL-Win32\bin\openssl.exe"
