### ISSUE TITLE
Dependencies don't mention that cmake 3.0+ is required

### ISSUE THREAD

**Issue by mark-summerfield** [pyside/pyside2-setup#41]
I can't build on Ubuntu 14.04 LTS (which is still within its lifespan) because it has cmake 2.8.12 and PySide requires 3.0+.

**Comment by ethanhs** [comment]
While 14.04 is currently in its lifespan, its end of life is in 2 months. I don't think 14.04 should be a concern for us, as it is going away soon. Just my opinion though. 

If you really need to do this on 14.04, [you can get cmake through ppas](https://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04)

And yes, somewhere we should state the min version of cmake required.
