### ISSUE TITLE
Dependencies for Linux don't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by mark-summerfield** [pyside/pyside2-setup#42]
(Sorry if this is a duplicate, can't see the first time I wrote it.)

The first apt-get line mentions python-dev (Python 2.7) with no mention of python3-dev (Python 3); although I used python3-dev.

The second apt-get line mentions libqt5quickwidgets5 which doesn't exist in Ubuntu 14.04 LTS.

The python setup.py line doesn't mention using python3; also shouldn't it simply say something like:

To install for Python 2 use:

sudo python setup.py install

Or for a local install

python setup.py install --user

If you want to use Python 3, use python3 rather than python.

If the install fails, try giving the installer the specific paths to the components it needs, by adding these arguments (with the correct paths of course): --qmake=/usr/bin/qmake --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl

**Comment by ethanhs** [comment]
Your points on python 2 vs 3 are well taken. PySide 2 is still not really ready for general use, so we are more focusing on fixing the bindings over adding documentation right now, so there are definitely areas where we need to clarify and update documentation.

You are correct in that libqt5quickwidgets5 is not available on 14.04. I suggest you read the [travis build script](https://github.com/PySide/pyside2-setup/blob/master/.travis.yml), as Travis uses a 14.04 build environment. If you require the version of Qt that ships with trusty, things may be more complicated.
