### ISSUE TITLE
QtWebKit not being built?

### ISSUE THREAD

**Issue by aschokking** [pyside/pyside2-setup#44]
I'm attempting to build PySide2 on Ubuntu 16.04.
I installed the dependencies and ran `sudo python setup.py install --qmake=/usr/bin/qmake --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl` which succeeded. However it looks like there's no PySide2.QtWebKit package installed and when I went back and looked at the build logs there are these suspicious messages:

```
CMake Warning at PySide2/CMakeLists.txt:18 (find_package):
  By not providing "FindQt5WebKit.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5WebKit", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKit" with
  any of the following names:

    Qt5WebKitConfig.cmake
    qt5webkit-config.cmake

  Add the installation prefix of "Qt5WebKit" to CMAKE_PREFIX_PATH or set
  "Qt5WebKit_DIR" to a directory containing one of the above files.  If
  "Qt5WebKit" provides a separate development package or SDK, be sure it has
  been installed.
-----------------------------------------------------------
module Qt5Core found
module Qt5Concurrent found
module Qt5Gui found
module Qt5Widgets found
module Qt5PrintSupport found
module Qt5Xml found
module Qt5XmlPatterns found
-- optional module Qt5Svg skipped
module Qt5PrintSupport found
module Qt5Sql found
-- optional module Qt5Designer skipped
-- optional module Qt5UiTools skipped
module Qt5Test found
module Qt5Network found
-- optional module Qt5WebKit skipped
-- optional module Qt5WebKitWidgets skipped
```

It looks like QtWebKit is expected to be there in general since I've seen test files reference the package, is there something else I might be missing to get it included?

**Comment by aschokking** [comment]
Here are the contents of the produced egg:
```
vagrant@vagrant:/usr/local/lib/python2.7/dist-packages/PySide2-2.0.0.dev0-py2.7-linux-x86_64.egg/PySide2$ ls
examples                                        libshiboken2-python2.7-x86_64-linux-gnu.so.2.0.0  QtPrintSupport.x86_64-linux-gnu.so  shiboken2
include                                         pyside2-lupdate                                   QtSql.x86_64-linux-gnu.so           shiboken2.so
__init__.py                                     pyside2-rcc                                       QtTest.x86_64-linux-gnu.so          typesystems
__init__.pyc                                    QtConcurrent.x86_64-linux-gnu.so                  QtWidgets.x86_64-linux-gnu.so       _utils.py
libpyside2-python2.7-x86_64-linux-gnu.so.2.0    QtCore.x86_64-linux-gnu.so                        QtXmlPatterns.x86_64-linux-gnu.so   _utils.pyc
libpyside2-python2.7-x86_64-linux-gnu.so.2.0.0  QtGui.x86_64-linux-gnu.so                         QtXml.x86_64-linux-gnu.so
libshiboken2-python2.7-x86_64-linux-gnu.so.2.0  QtNetwork.x86_64-linux-gnu.so                     scripts
```

**Comment by dbrnz** [comment]
What version of Qt comes with Ubuntu 16.04? Webkit is no longer part of 
Qt as of Qt 5.6.

**Comment by aschokking** [comment]
Ah good question. Looks like it's 5.4.2. I had also tried it in a 15.10 vm earlier and was seeing the same thing. 

It looks like libqt5webkit5 is installed `ii  libqt5webkit5:amd64                  5.4.2+dfsg-1ubuntu2.1              amd64        Web content engine library for Qt` which was one of the dependencies listed https://github.com/PySide/pyside2/wiki/Dependencies .

**Comment by thopiekar** [comment]
@aschokking Why building PySide2 if there is a PPA? :wink: 
https://launchpad.net/~thopiekar/+archive/ubuntu/pyside-git

**Comment by aschokking** [comment]
Thanks for the pointer @thopiekar! Had looked a few months back and didn't see one before I thought, will try that out instead now 👍

**Comment by thopiekar** [comment]
No problem :wink: 
Remember that these packages are nightly builds, so breakages here will land there quickly.

**Comment by thopiekar** [comment]
Btw. "QtWebkit" is still there. They are just using a Chromium engine now for web rendering..

**Comment by wooque** [comment]
Installing libqt5webkit5-dev seem to fix this issue
