### ISSUE TITLE
Repo clone instructions

### ISSUE THREAD

**Issue by spikeynick** [PySide/pyside2-setup#48]
I'm not sure if this is the correct place for this.  Would it be possible to add repo clone instructions to the Getting Started wiki page (https://wiki.qt.io/PySide2_GettingStarted).  It would have saved me time and headache if it was stated that the repo needs to be checked out with clone --recursive, otherwise the submodules don't get pulled.

**Comment by ethanhs** [comment]
Hello @spikeynick this is no longer the main repository for PySide2. Development has moved under the umbrella of the Qt Company. Bug reports go [here](https://bugreports.qt.io/browse/PYSIDE/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel). It is a good suggestion.

Unintuitively, you can also just run setup.py, as that is supposed to grab all the submodules for you.

**Comment by techtonik** [comment]
That's most unfortunate that Qt Project still uses private architecture for issue management and it's not GitHub.

**Comment by ethanhs** [comment]
@techtonik what do you mean by "private architecture"? Anyone with a Qt account can open or comment on a bug report.

**Comment by techtonik** [comment]
I meant `proprietary` or `not open source`. GitHub is proprietary, GitLab is not.
