### ISSUE TITLE
setup.py ran successfully on Linux Mint 18.1....Install??

### ISSUE THREAD

**Issue by joncarr** [pyside/pyside2-setup#49]
First off, apologies for my ignorance but python is relatively new to me.

I am running Linux Mint 18.1 Cinnamon.  I grabbed all the dependencies for PySide2 and was able to run the setup.py successfully.  I looked in the wiki for further installation instructions following setup.py but can't seem to find anything.  Is there a next step?  Add a folder into my packages to be able to use PySide2???  Again, python is new to me so please bear with me here.  How do I make PySide2 usable after running setup.py?  It looks to have only updates the source files??  Maybe setup.py wasn't successful?? It says, Error no command supplied at the bottom.....

sudo python3 setup.py --qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl
Initializing submodules for PySide2 version 2.0.0.dev0
Submodule path 'sources/pyside2': checked out '131fdfd1a89a257094148c07c630f136752c703b'
Submodule path 'sources/pyside2-tools': checked out '1eb5ccf5208d775e1e70b2332d9a61df00612801'
Submodule path 'sources/shiboken2': checked out '9b4a3cfcee9cfd5a98c33b29ec4ecfd8d3e973f4'
Submodule path 'wiki': checked out 'ac1b69fabc1a9f81da585fe1a1aa4188862ced66'
Entering 'sources/pyside2'
Entering 'sources/pyside2-examples'
Entering 'sources/pyside2-tools'
Entering 'sources/shiboken2'
Entering 'wiki'
Entering 'sources/pyside2'
From https://github.com/PySide/pyside2
 * branch            master     -> FETCH_HEAD
Updating 131fdfd..03c250d
Fast-forward
 CMakeLists.txt                   |  4 +++
 PySide2/CMakeLists.txt           |  8 ++++++
 PySide2/QtGui/CMakeLists.txt     |  5 ++++
 PySide2/QtGui/fixup_headers.py   | 59 ++++++++++++++++++++++++++++++++++++++++
 PySide2/QtHelp/CMakeLists.txt    |  5 ++++
 PySide2/QtHelp/fixup_headers.py  | 55 +++++++++++++++++++++++++++++++++++++
 libpyside/dynamicqmetaobject.cpp | 23 +++++++++++-----
 libpyside/pysideproperty.cpp     |  3 ++
 8 files changed, 155 insertions(+), 7 deletions(-)
 create mode 100644 PySide2/QtGui/fixup_headers.py
 create mode 100644 PySide2/QtHelp/fixup_headers.py
Entering 'sources/pyside2-examples'
From https://github.com/PySide/pyside2-examples
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Entering 'sources/pyside2-tools'
From https://github.com/PySide/pyside2-tools
 * branch            master     -> FETCH_HEAD
Updating 1eb5ccf..3b0cf7c
Fast-forward
 CMakeLists.txt                        |  7 +++++++
 pyside2uic/Compiler/qobjectcreator.py | 16 +++++++++++++++-
 pyside2uic/objcreator.py              |  3 ++-
 3 files changed, 24 insertions(+), 2 deletions(-)
Entering 'sources/shiboken2'
From https://github.com/PySide/shiboken2
 * branch            master     -> FETCH_HEAD
Updating 9b4a3cf..3a496b7
Fast-forward
 CMakeLists.txt                            | 7 +++++++
 generator/shiboken2/shibokengenerator.cpp | 4 ++++
 tests/libsample/photon.cpp                | 2 --
 tests/libsample/simplefile.cpp            | 4 ++--
 4 files changed, 13 insertions(+), 4 deletions(-)
Entering 'wiki'
From https://github.com/PySide/pyside2.wiki
 * branch            master     -> FETCH_HEAD
Updating ac1b69f..ed7b7ce
Fast-forward
 Debugging-Shiboken-on-Mac-OS-X.md                  |   2 +-
 Dependencies.md                                    |   6 +-
 Home.md                                            |   5 +
 My-Practice:-Porting-python-scripts-to-PySide2.md  |  98 ----------------
 My_Practice_:_Porting_python_scripts_to_PySide2.md | 123 +++++++++++++++++++++
 Project-Test-Status.md                             |  31 +++---
 6 files changed, 149 insertions(+), 116 deletions(-)
 delete mode 100644 My-Practice:-Porting-python-scripts-to-PySide2.md
 create mode 100644 My_Practice_:_Porting_python_scripts_to_PySide2.md
Checking out submodule shiboken2 to branch master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Checking out submodule pyside2 to branch master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Checking out submodule pyside2-tools to branch master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Checking out submodule pyside2-examples to branch master
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Removing /home/jec/pyside2-setup/pyside_package
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by dbrnz** [comment]
Try `python setup.py --help-commands`. My guess is that you want `install`.


Dave

**Comment by ethanhs** [comment]
please also note the code is not maintained in this repo. You probably want to use https://code.qt.io/cgit/pyside/pyside-setup. Also, to answer your question, you want to install like `python setup.py install --cmake=... --qmake=...` where the ... each point to your cmake and qmake executables (its better if you provide the full path).
