### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by machinekoder** [pyside/pyside2-setup#50]
The link to the Qt repository in the description is dead.

**Comment by ethanhs** [comment]
Yes the link is correct in the pyside2 repo, but wrong here. [The link is here](https://code.qt.io/cgit/pyside/pyside.git).

**Comment by machinekoder** [comment]
Thanks. I still think this should corrected in the header as well.

**Comment by ethanhs** [comment]
I don't have the rights to do so, but I agree. @ctismer. Could you fix this?

**Comment by BrenBarn** [comment]
Link is still dead four months later. . .
