### ISSUE TITLE
Error configuring shiboken2

### ISSUE THREAD

**Issue by otakbeku** [pyside/pyside2-setup#52]
I'm getting the following error when trying to build it.

    running install
    running build
    Removing G:\pyside-setup\pyside_package
    Python architecture is 64bit
    nmake was found in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe
    Inserting path "G:\pyside-setup\pyside3_install\py3.5-qt5.9.1-64bit-release\bin" to environment
    ==============================
    Package version: 2.0.0.dev0
    Build type: Release
    Build tests: False
    ---
    Make path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe
    Make generator: NMake Makefiles 
    Make jobs: -j4
     ---
     Script directory: G:\pyside-setup
     Sources directory: G:\pyside-setup\sources
     Build directory: G:\pyside-setup\pyside3_build\py3.5-qt5.9.1-64bit-release
     Install directory: G:\pyside-setup\pyside3_install\py3.5-qt5.9.1-64bit-release
     Python site-packages install directory: G:\pyside-setup\pyside3_install\py3.5-qt5.9.1-64bit-
     release\Lib\site-packages
     ---
     Python executable: G:\Anaconda3\python.exe
     Python includes: G:\Anaconda3\include
     Python library: G:\Anaconda3\libs\python35.lib
     Python prefix: G:\Anaconda3
     Python scripts: G:\Anaconda3\Scripts
     ---
     Qt qmake: G:\Qt5\5.9.1\msvc2015_64\bin\qmake.exe
     Qt version: 5.9.1 
     Qt bins: G:/Qt5/5.9.1/msvc2015_64/bin
     Qt docs: G:/Qt5/Docs/Qt-5.9.1
     Qt plugins: G:/Qt5/5.9.1/msvc2015_64/plugins
     ---
     OpenSSL libs: C:/OpenSSL-Win32/bin
     ==============================
     Building module shiboken2...
     Deleting module build folder G:\pyside-setup\pyside3_build\py3.5-qt5.9.1-64bit-release\shiboken2...
     Creating module build folder G:\pyside-setup\pyside3_build\py3.5-qt5.9.1-64bit-release\shiboken2...
     Configuring module shiboken2 (G:\pyside-setup\sources\shiboken2)...
     Running process in G:\pyside-setup\pyside3_build\py3.5-qt5.9.1-64bit-release\shiboken2: 
     G:\CMake\bin\cmake.exe -G "NMake Makefiles" -DBUILD_TESTS=False -
     DQt5Help_DIR=G:/Qt5/Docs/Qt-5.9.1 -DCMAKE_BUILD_TYPE=Release -
       DCMAKE_INSTALL_PREFIX=G:\pyside-setup\pyside3_install\py3.5-qt5.9.1-64bit-release G:\pyside-
      setup\sources\shiboken2 -DPYTHON_EXECUTABLE=G:\Anaconda3\python.exe -
        DPYTHON_INCLUDE_DIR=G:\Anaconda3\include -
       DPYTHON_LIBRARY=G:\Anaconda3\libs\python35.lib -DQT_SRC_DIR=G:/Qt5/5.9.1/msvc2015_64 -
        DCMAKE_INSTALL_RPATH_USE_LINK_PATH=yes -DUSE_PYTHON_VERSION=3.3
       -- The C compiler identification is MSVC 19.0.24215.1
      -- The CXX compiler identification is MSVC 19.0.24215.1
       -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- 
      broken
       CMake Error at G:/CMake/share/cmake-3.9/Modules/CMakeTestCCompiler.cmake:51 (message):
       The C compiler "C:/Program Files (x86)/Microsoft Visual Studio
          14.0/VC/bin/cl.exe" is not able to compile a simple test program.

        It fails with the following output:

               Change Dir: G:/pyside-setup/pyside3_build/py3.5-qt5.9.1-64bit-
        release/shiboken2/CMakeFiles/CMakeTmp

               Run Build Command:"nmake" "/NOLOGO" "cmTC_40c36\fast"

              "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\nmake.exe" -f
                 CMakeFiles\cmTC_40c36.dir\build.make /nologo -L
                       CMakeFiles\cmTC_40c36.dir\build

                          Building C object CMakeFiles/cmTC_40c36.dir/testCCompiler.c.obj

                     C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe
                       @C:\Users\blackbox\AppData\Local\Temp\nm35F8.tmp

             testCCompiler.c

                   Linking C executable cmTC_40c36.exe

               G:\CMake\bin\cmake.exe -E vs_link_exe --intdir=CMakeFiles\cmTC_40c36.dir
                   --manifests -- C:\PROGRA~2\MICROS~1.0\VC\bin\link.exe /nologo
                   @CMakeFiles\cmTC_40c36.dir\objects1.rsp
                    @C:\Users\blackbox\AppData\Local\Temp\nm37DD.tmp

                 RC Pass 1 failed to run.

               NMAKE : fatal error U1077: 'G:\CMake\bin\cmake.exe' : return code
               '0xffffffff'

                 Stop.

                   NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio
                      14.0\VC\bin\nmake.exe"' : return code '0x2'

                         Stop.

                    CMake will not be able to correctly generate this project.
                    Call Stack (most recent call first):
            CMakeLists.txt:2 (project)

                   -- Configuring incomplete, errors occurred!
                See also "G:/pyside-setup/pyside3_build/py3.5-qt5.9.1-64bit-
              release/shiboken2/CMakeFiles/CMakeOutput.log".
              See also "G:/pyside-setup/pyside3_build/py3.5-qt5.9.1-64bit-
              release/shiboken2/CMakeFiles/CMakeError.log".
               error: Error configuring shiboken2

here's the cmake log:
[CMakeOutput.log](https://www.dropbox.com/s/qxpfm8dtax8cjcy/CMakeOutput.log?dl=0)
[CMakeError.log](https://www.dropbox.com/s/bjaijadvo1ynt0y/CMakeError.log?dl=0)

**Comment by universvm** [comment]
I know this has been open for about a year now, but did you manage to solve your problem? I have the exact same problem in MacOS.
