### ISSUE TITLE
Python27 - this application failed to start because no qt platform plugin could be initialized

### ISSUE THREAD

**Issue by ManPython** [pyside/pyside2-setup#57]
Python27 - this application failed to start because no qt platform plugin could be initialized..
Any of Pyside2 not working on x64 Python27 
http://download.qt.io/snapshots/ci/pyside/5.9/latest/pyside2/PySide2-5.9.0a1.dev1528389443-5.9.6-cp27-cp27m-win_amd64.whl

import sys
from PySide2.QtWidgets import QApplication, QLabel
if __name__ == "__main__":

    app = QApplication([])

    label = QLabel("Hello World")

    label.show()
    sys.exit(app.exec_())`

![pyside2](https://user-images.githubusercontent.com/25403861/41814501-86338804-774e-11e8-81d0-9e8c0edee5b8.png)

Working well dedicated Py36 version.
The philosophy to omit classic comand pip install --upgrade PySide2 is trouble in case of hashed versions of PySide2

**Comment by giumas** [comment]
Similar issue using the hello world example with Python 3.6 and the latest PyPi wheel (5.11.1):

![python_2018-07-27_12-44-11](https://user-images.githubusercontent.com/2849257/43334236-d6d58c92-919a-11e8-83de-eaa5a6a04c15.png)

**Comment by giumas** [comment]
If I run the app after "set QT_DEBUG_PLUGINS=1", I get:
```
QFactoryLoader::QFactoryLoader() checking directory path "C:/Users/xxxxx/AppData/Local/py3/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
```
Such a folder does not exist. So if I add the right path to the code (using `QCoreApplication.addLibraryPath`), it works:

```
import sys
from PySide2 import QtCore, QtGui, QtWidgets


def main():
    QtCore.QCoreApplication.addLibraryPath(r"C:\Users\xxxxxi\AppData\Local\py3\Lib\site-packages\PySide2\plugins")
    app = QtWidgets.QApplication([])

    main_win = QtWidgets.QMainWindow()
    main_win.show()

    sys.exit(app.exec_())
```

**Comment by cmaureir** [comment]
Follow the discussion in https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-761
