### ISSUE TITLE
Missing file qsysinfo_wrapper.cpp

### ISSUE THREAD

**Issue by buddylindsey** [PySide/pyside2-setup#6]
Going through the steps. For most errors I just installed something I missed for Qt5 install.

However, I got this issue, and it seems like something is gone altogether.

```
c++: error: /home/buddy/Programming/python/pyside2-setup/pyside_build/py3.4-qt5.4.1-64bit-release/pyside2/PySide2/QtCore/PySide2/QtCore/qsysinfo_wrapper.cpp: No such file or directory
c++: fatal error: no input files
compilation terminated.
PySide2/QtCore/CMakeFiles/QtCore.dir/build.make:2173: recipe for target 'PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsysinfo_wrapper.cpp.o' failed
make[2]: *** [PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsysinfo_wrapper.cpp.o] Error 4
CMakeFiles/Makefile2:229: recipe for target 'PySide2/QtCore/CMakeFiles/QtCore.dir/all' failed
make[1]: *** [PySide2/QtCore/CMakeFiles/QtCore.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
error: Error compiling pyside2
```

Any ideas?

**Comment by ctismer** [comment]
On 26.09.15 02:46, Buddy Lindsey, Jr. wrote:
>
> Going through the steps. For most errors I just installed something I
> missed for Qt5 install.
>
> However, I got this issue, and it seems like something is gone altogether.
>
> |c++: error:
> /home/buddy/Programming/python/pyside2-setup/pyside_build/py3.4-qt5.4.1-64bit-release/pyside2/PySide2/QtCore/PySide2/QtCore/qsysinfo_wrapper.cpp:
> No such file or directory c++: fatal error: no input files compilation
> terminated. PySide2/QtCore/CMakeFiles/QtCore.dir/build.make:2173:
> recipe for target
> 'PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsysinfo_wrapper.cpp.o'
> failed make[2]: ***
> [PySide2/QtCore/CMakeFiles/QtCore.dir/PySide2/QtCore/qsysinfo_wrapper.cpp.o]
> Error 4 CMakeFiles/Makefile2:229: recipe for target
> 'PySide2/QtCore/CMakeFiles/QtCore.dir/all' failed make[1]: ***
> [PySide2/QtCore/CMakeFiles/QtCore.dir/all] Error 2 Makefile:117:
> recipe for target 'all' failed make: *** [all] Error 2 error: Error
> compiling pyside2 |
>
> Any ideas?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PySide/pyside2-setup/issues/6>.
>

About installation: The README.md should have brought you to the wiki
with the dependencies...

Yes, I expected something like this.
I moved the sysinfo object out of the main XML file
and created special versions for Windows and OS X.

Something similar is now missing in

typesystem_core_x11.xml

Patches welcome, if QtCore imports successfully :-)

-- 
Christian Tismer             :^)   tismer@stackless.com
Software Consulting          :     http://www.stackless.com/
Karl-Liebknecht-Str. 121     :     https://github.com/PySide
14482 Potsdam                :     GPG key -> 0xFB7BEE0E
phone +49 173 24 18 776  fax +49 (30) 700143-0023

**Comment by thopiekar** [comment]
@ctismer I would say it is fixed, isn't it? :smiley:

**Comment by ctismer** [comment]
sure :+1:
