### ISSUE TITLE
Use Continuous integration

### ISSUE THREAD

**Issue by ethanhs** [pyside/pyside2-setup#9]
This would avoid issues such as merged code that breaks things and makes things easier for maintainers. For Windows  there is Appveyor. For Debian there is Travis of course. Once set up this would save a lot of resources. OS X would be harder to find, unless someone contributes a Mac. ;-)

**Comment by ctismer** [comment]
Would you do that? I can put in a virtual Mac, 8-core, legal. Go ahead!

**Comment by IronManMark20** [comment]
For Appveyor I need to be a contributer (you could add me in settings). It appears Travis also needs me to be added to the PySide orginization. You could remove me after I am done if you want. For the Mac, I will need remote access, which we probably shouldn't discuss here.

**Comment by The-Compiler** [comment]
FWIW, Travis also offers OS X if you mail support@travis-ci.com and ask nicely, or at least that was the case when I did a few months ago.

* Example build: https://travis-ci.org/The-Compiler/qutebrowser/builds/82678449
* `.travis.yml`: https://github.com/The-Compiler/qutebrowser/blob/master/.travis.yml

**Comment by ctismer** [comment]
@IronManMark20 I added you to the community team. Please let me know if that works for you.

**Comment by ctismer** [comment]
@IronManMark20 correction: I am creating a new team for exactly the pyside2 repositories and will add you there as a collaborator.

**Comment by ctismer** [comment]
There is the new PySide2-devel team. It has write access to all related repos. Please let me know if that is sufficient. Currently I added @IronManMark20 @The-Compiler @thopiekar to the team.
Do teams have a communication channel?

**Comment by ctismer** [comment]
For checking in certain stuff:
I recommend to create a new branch for everything that isn't trivial (i.e. everything that might break someone's work). You can pick a name that clarifies the purpose or who's branch it is. When things are done, we can merge things into master.

**Comment by thopiekar** [comment]
Sounds good. Additionally a branch called "stable" could be useful, were stable code + bugfixes (no new features) are hosted - just for the future...

**Comment by IronManMark20** [comment]
@ctismer, thanks for adding us! @The-Compiler, thanks for letting us know, that will simplify things substantially. I'll contact the people at Travis today, and start on the other CI pushes.

**Comment by IronManMark20** [comment]
@thopiekar i believe that is the idea behind releases. So we can make releases when we feel that things are stable enough, but things like that should be discussed, speeking of, no @ctismer, i dont believe there is a github tool, but there are some 3rd party tools such as gitter, and we could use something else entirely.

**Comment by ctismer** [comment]
Well, those tools... I would like an email that is about PySide2, but without talking all the time. I was used to that on the PyPy IRC, quite ok but very time consuming.
Now I started to work with continuum.io, and they use FlowDock for a lot of talking.
In the end, I am annoyed by too much talking ;-)
But that is probably a no-brainer, if we don'd let everybody participate.

So I have set one up -- let's see if that makes sense, or better IRC, or just good-ole mailman...

**Comment by The-Compiler** [comment]
So I tried to set up a `.travis.yml` for the `pyside2` repo which clones `pyside2-setup` and then replaces the `pyside2` submodule with the repo: https://github.com/The-Compiler/pyside2/blob/master/.travis.yml

However, it seems [compiling Shiboken fails](https://travis-ci.org/The-Compiler/pyside2/builds/91986982). Any idea what's going on there?

**Comment by empyrical** [comment]
IMO it might be best if the `pyside2-setup` and `pyside2` repos were eventually combined into one repo, as it would make CI much easier and probably remedy that LaunchPad.net problem that was mentioned in another issue. Should also make the shiboken submodule optional, and make it so you can provide a `--shiboken-dir` option to setup.py to point to an existing build; and if it's not provided then it'd grab it from GitHub automatically.

Would be best to wait until later though because the current layout works and changing things right now would be a needless complication.

**Comment by thopiekar** [comment]
Right, while importing code from github (git) to Launchpad (bzr) the
repository is being converted to bzr. Bzr can't handle submodules to
importing hit repositories with submodules fail.

Thank you for remembering that problem :)
